server:
  port: 8060
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: fee-collection-service
          uri: lb://fee-collection-service
          predicates:
            - Path=/fees/**
        - id: receipt-service
          uri: lb://receipt-service
          predicates:
            - Path=/receipts/**
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/students/**